services:
    database:
        image: mariadb:latest
        container_name: supchat_db
        environment:
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - ./server/database/sql:/docker-entrypoint-initdb.d
        ports:
            - "8000:8000"

    server:
        image: node:latest
        container_name: supchat_server
        working_dir: /app
        volumes:
            - ./server:/app
        ports:
            - "3000:3000"
        depends_on:
            - database
        environment:
            DB_HOST: database
            DB_USER: root
            DB_PASSWORD: root
        command: ["node", "index.js"]
    
    web:
        image: node:latest
        container_name: supchat_web
        working_dir: /app
        volumes:
            - ./client/web:/app
        ports:
            - "5000:5000"
        depends_on:
            - database
            - server
        environment:
            NODE_OPTIONS: --openssl-legacy-provider
        command: ["node", "run", "react-scripts", "start"]