import { useState } from 'react';
import { View, Text, ScrollView, Linking } from 'react-native';
import styles from './PrivacyPageStyles';

const PrivacyPage = () => {
  const [theme] = useState('light');

  return (
    <View style={[styles.container, theme === 'dark' ? styles.dark : styles.light]}>
      <View style={styles.privacyContainer}>
        <ScrollView showsVerticalScrollIndicator={false}>
          <View style={styles.privacyBox}>
            <Text style={styles.title}>Politique de confidentialité de Supchat</Text>
            <Text style={styles.line}>───────────────────────</Text>
            <Text>Date d'entrée en vigueur : 01 Janvier 2025</Text>
            <Text>Dernière mise à jour : 03 janvier 2025</Text>

            <Text style={styles.section}>1. Introduction</Text>
            <Text style={styles.paragraph}>Chez Supchat, nous attachons une grande importance à la protection de vos données personnelles. Nous nous engageons à respecter la confidentialité de vos informations et à traiter vos données conformément aux exigences légales en matière de protection des données, notamment le Règlement Général sur la Protection des Données (RGPD) de l'Union Européenne.</Text>
            <Text style={styles.paragraph}>Cette politique de confidentialité a pour but de vous informer sur la manière dont nous collectons, utilisons, partageons et protégeons vos données personnelles lorsque vous utilisez notre application Supchat. Elle explique également vos droits en tant qu'utilisateur concernant vos informations personnelles et comment vous pouvez les exercer.</Text>
            <Text style={styles.paragraph}>Nous collectons des informations vous concernant uniquement dans le cadre des finalités légitimes et spécifiques définies ci-dessous. Nous ne traiterons vos données que pour les besoins strictement nécessaires à la fourniture de nos services et veillerons à ce que vos informations soient conservées en toute sécurité et ne soient utilisées que de manière transparente.</Text>
            <Text style={styles.paragraph}>En utilisant Supchat, vous acceptez que nous collections, traitions et stockions vos données personnelles conformément à cette politique de confidentialité. Nous vous encourageons à lire attentivement cette politique et à nous contacter si vous avez des questions ou des préoccupations concernant la manière dont vos données sont traitées.</Text>
            <Text style={styles.paragraph}>Conformément au RGPD, nous vous informons également que vous avez le droit d'accéder, de rectifier, de supprimer ou de restreindre le traitement de vos données personnelles, ainsi que d'exercer d'autres droits en lien avec la protection de vos informations personnelles, tels qu'expliqués dans la section dédiée ci-dessous.</Text>

            <Text style={styles.section}>2. Informations que nous collectons</Text>
            <Text style={styles.paragraph}>Lorsque vous utilisez Supchat, nous collectons divers types d'informations afin de vous fournir une expérience optimale et de vous permettre d'utiliser nos services de manière efficace. Ces informations peuvent être collectées directement auprès de vous ou automatiquement via votre utilisation de notre application. Conformément au RGPD, nous nous engageons à ne collecter que les informations nécessaires aux finalités pour lesquelles elles sont traitées.</Text>
            <Text style={styles.paragraph}>Les types d'informations que nous collectons incluent :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Informations personnelles :</Text> Ces informations vous permettent de créer et de gérer votre compte Supchat. Elles incluent votre nom, adresse e-mail, numéro de téléphone, et autres informations d'identification personnelle que vous fournissez volontairement lors de l'inscription ou de l'utilisation de l'application.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Informations d'utilisation :</Text> Ces données concernent votre utilisation de Supchat et nous aident à améliorer l'expérience utilisateur. Elles incluent des informations sur vos interactions avec l'application, telles que les messages que vous envoyez ou recevez, vos connexions, les groupes ou canaux auxquels vous appartenez, ainsi que vos paramètres et préférences (par exemple, les notifications activées ou désactivées).</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Informations techniques :</Text> Nous collectons des informations techniques concernant les appareils et les environnements logiciels que vous utilisez pour accéder à Supchat. Cela inclut votre adresse IP, le type et la version du navigateur que vous utilisez, les informations relatives à votre appareil (comme son modèle, son système d'exploitation, etc.), et des données sur la manière dont vous accédez à nos services, telles que des journaux d'erreur ou des événements système. Ces données sont collectées afin d'assurer la performance et la sécurité de notre application.</Text>
            <Text style={styles.paragraph}>Les informations collectées peuvent être utilisées à diverses fins, telles que l'amélioration de la performance de l'application, la personnalisation de votre expérience, la communication avec vous au sujet de nouvelles fonctionnalités ou de mises à jour, et pour assurer la sécurité et la conformité de notre service avec la législation applicable.</Text>
            <Text style={styles.paragraph}>Conformément au principe de minimisation des données du RGPD, nous veillons à ne collecter que les informations strictement nécessaires à ces fins et à les conserver pendant une durée limitée, conformément aux exigences légales ou contractuelles.</Text>

            <Text style={styles.section}>3. Utilisation de vos informations</Text>
            <Text style={styles.paragraph}>Nous utilisons vos informations personnelles de manière transparente et conforme au RGPD pour vous offrir une expérience optimale sur Supchat. Les informations collectées sont utilisées pour diverses finalités légitimes, que nous détaillons ci-dessous. Ces utilisations sont essentielles à la fourniture de nos services et à l'amélioration de l'application.</Text>
            <Text style={styles.paragraph}>Nous utilisons vos informations pour :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Fournir, maintenir et améliorer nos services :</Text> Nous utilisons vos informations pour exploiter pleinement les fonctionnalités de Supchat, résoudre des problèmes techniques, offrir une assistance et maintenir la sécurité de l'application. Cela inclut la gestion de vos messages, connexions et interactions avec d'autres utilisateurs, ainsi que la mise à jour de l'application pour ajouter de nouvelles fonctionnalités.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Personnaliser votre expérience dans Supchat :</Text> Nous utilisons vos informations pour adapter et personnaliser votre expérience sur notre plateforme. Cela peut inclure la personnalisation de l'interface, la gestion de vos préférences de notifications, et l'adaptation des contenus ou fonctionnalités proposés en fonction de vos comportements et de vos choix.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Communiquer avec vous concernant des mises à jour, promotions et informations importantes :</Text> Nous pouvons utiliser vos informations pour vous envoyer des notifications concernant les mises à jour de l'application, des nouvelles fonctionnalités, des promotions ou des informations importantes relatives à notre service. Nous vous informerons toujours de toute communication marketing ou promotionnelle et vous aurez la possibilité de vous désinscrire à tout moment.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Analyser l'utilisation de l'application pour améliorer ses fonctionnalités :</Text> Nous utilisons les informations d'utilisation et techniques collectées pour analyser la performance de l'application, identifier les problèmes techniques, et améliorer les fonctionnalités. Cela peut inclure l'analyse des données relatives à l'utilisation de l'application pour détecter des tendances, comprendre les besoins des utilisateurs et prioriser les mises à jour.</Text>
            <Text style={styles.paragraph}>Dans le respect des principes du RGPD, nous nous engageons à ne traiter vos informations personnelles que pour des finalités spécifiques, légitimes et clairement définies. Nous veillons également à ce que vos informations soient utilisées de manière proportionnée et que les traitements soient limités à ce qui est nécessaire pour atteindre ces objectifs.</Text>
            <Text style={styles.paragraph}>Nous ne traitons vos données personnelles que dans la mesure où cela est nécessaire à la fourniture de nos services et nous mettons en place des mesures appropriées pour garantir leur sécurité.</Text>

            <Text style={styles.section}>4. Partage de vos informations</Text>
            <Text style={styles.paragraph}>Chez Supchat, nous nous engageons à ne pas vendre, échanger ou partager vos informations personnelles avec des tiers, sauf dans des circonstances spécifiques et légales. Nous respectons pleinement votre vie privée et nous nous assurons que vos données sont partagées uniquement lorsque cela est nécessaire pour fournir nos services ou en conformité avec la législation en vigueur.</Text>
            <Text style={styles.paragraph}>Nous pouvons partager vos informations dans les cas suivants :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Si nous avons votre consentement explicite pour partager vos informations :</Text> Dans certains cas, nous pourrions avoir besoin de votre consentement pour partager vos informations avec des tiers. Ce consentement sera toujours demandé de manière claire et transparente, et vous aurez la possibilité de le retirer à tout moment.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Pour répondre à des demandes légales ou pour se conformer aux lois en vigueur :</Text> Nous pourrions être amenés à partager vos informations personnelles si cela est requis par la loi ou pour répondre à une demande légale émanant d'une autorité publique (par exemple, en réponse à une ordonnance judiciaire, une enquête criminelle ou une demande d'une autorité compétente). Dans ce cas, nous nous assurons que la divulgation est limitée au strict nécessaire et que vos droits sont respectés.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Pour améliorer la sécurité ou résoudre des problèmes techniques avec nos services :</Text> Nous pourrions partager vos informations avec nos prestataires de services ou partenaires techniques dans le but d'améliorer la sécurité, d'analyser des problèmes techniques ou d'assurer le bon fonctionnement de nos services. Ces tiers sont soumis à des contrats stricts et doivent respecter les lois applicables en matière de protection des données. Ils n'ont accès à vos informations que dans le cadre des services qu'ils fournissent pour Supchat.</Text>
            <Text style={styles.paragraph}>Dans tous les cas, nous veillons à ce que le partage de vos informations soit limité à ce qui est nécessaire pour atteindre les objectifs légitimes mentionnés ci-dessus et à ce que vos données soient protégées de manière appropriée conformément au RGPD. Lorsque cela est possible, nous mettons en place des accords de traitement des données (DPA) pour garantir que toute entité tierce avec laquelle nous partageons vos données respecte les mêmes normes de confidentialité et de sécurité que celles que nous appliquons.</Text>

            <Text style={styles.section}>5. Sécurité des informations</Text>
            <Text style={styles.paragraph}>Chez Supchat, nous prenons très au sérieux la sécurité de vos informations personnelles. Nous mettons en place des mesures de sécurité techniques et organisationnelles appropriées pour protéger vos données contre tout accès non autorisé, toute altération, divulgation ou destruction accidentelle ou illicite. Ces mesures visent à garantir la confidentialité, l'intégrité et la disponibilité de vos informations personnelles.</Text>
            <Text style={styles.paragraph}>Les mesures que nous utilisons comprennent notamment :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Cryptage des données :</Text> Nous utilisons des technologies de cryptage modernes pour protéger vos informations pendant leur transmission, en particulier pour les communications sensibles comme les messages et autres données personnelles.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Contrôles d'accès :</Text> L'accès à vos informations est strictement limité aux employés et prestataires de services ayant besoin de ces informations pour accomplir leurs fonctions. Nous avons mis en place des systèmes d'authentification et de contrôle des accès pour garantir que seules les personnes autorisées puissent consulter ou modifier vos données.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Sauvegardes régulières :</Text> Nous effectuons régulièrement des sauvegardes de vos données afin de minimiser les risques de perte ou d'altération de celles-ci en cas d'incident technique ou de catastrophe naturelle.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Surveillance continue :</Text> Nous surveillons en permanence nos systèmes pour détecter toute activité suspecte ou toute violation de sécurité, afin de réagir rapidement à toute menace potentielle.</Text>
            <Text style={styles.paragraph}>Cependant, bien que nous mettions en œuvre des mesures de sécurité robustes, il est important de noter qu'aucune méthode de transmission de données sur Internet ou de stockage électronique n'est totalement sécurisée. En conséquence, nous ne pouvons pas garantir la sécurité absolue de vos informations personnelles. Nous vous encourageons également à prendre des précautions pour protéger vos informations personnelles, notamment en choisissant des mots de passe forts et en évitant de partager vos informations d'identification avec d'autres.</Text>
            <Text style={styles.paragraph}>En cas de violation de la sécurité des données, nous nous engageons à vous informer rapidement conformément aux obligations prévues par le RGPD, et à prendre les mesures nécessaires pour limiter l'impact de cette violation.</Text>
            <Text style={styles.paragraph}>En utilisant Supchat, vous reconnaissez que, malgré nos efforts pour protéger vos informations, il existe toujours un risque résiduel lié à la sécurité sur Internet.</Text>

            <Text style={styles.section}>6. Vos droits</Text>
            <Text style={styles.paragraph}>Conformément au Règlement Général sur la Protection des Données (RGPD), vous disposez de plusieurs droits concernant vos informations personnelles. Ces droits vous permettent de mieux contrôler la manière dont vos données sont collectées, utilisées et partagées par Supchat. Nous nous engageons à respecter vos droits et à vous fournir les moyens d'exercer ces derniers de manière simple et transparente.</Text>
            <Text style={styles.paragraph}>Vous avez les droits suivants concernant vos informations personnelles :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Accéder à vos informations personnelles que nous détenons :</Text> Vous avez le droit de demander une copie des informations personnelles que nous détenons à votre sujet. Nous vous fournirons ces informations dans un format compréhensible et lisible, sous réserve de certaines exceptions prévues par la loi.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Demander la correction ou la suppression de vos informations personnelles :</Text> Si vos informations personnelles sont inexactes ou incomplètes, vous avez le droit de demander leur correction. Vous pouvez également demander la suppression de vos informations personnelles dans certaines situations, par exemple si les données ne sont plus nécessaires aux fins pour lesquelles elles ont été collectées ou si vous retirez votre consentement (lorsque le traitement est basé sur ce consentement).</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Vous opposer à l'utilisation de vos informations pour certaines finalités :</Text> Vous avez le droit de vous opposer à l'utilisation de vos informations personnelles dans certains cas, comme le traitement à des fins de marketing direct ou lorsque nous traitons vos données sur la base de nos intérêts légitimes. Si vous exercez ce droit, nous cesserons d'utiliser vos informations à ces fins, sauf si nous avons des raisons légales impérieuses de continuer à les traiter.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Demander la limitation du traitement de vos informations :</Text> Vous pouvez demander que nous limitions le traitement de vos données personnelles dans certaines circonstances, par exemple si vous contestez l'exactitude des données ou si vous vous opposez à leur traitement.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Demander la portabilité de vos informations :</Text> Dans certains cas, vous avez le droit de recevoir les informations personnelles que vous nous avez fournies dans un format structuré, couramment utilisé et lisible par machine, et de les transmettre à un autre responsable du traitement.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Retirer votre consentement :</Text> Si le traitement de vos données personnelles repose sur votre consentement (par exemple pour les communications marketing), vous avez le droit de retirer ce consentement à tout moment. Le retrait de votre consentement n'affecte pas la légalité du traitement effectué avant ce retrait.</Text>
            <Text style={styles.paragraph}>Pour exercer ces droits, vous pouvez nous contacter directement via les informations de contact fournies dans cette politique de confidentialité. Nous nous efforcerons de répondre à votre demande dans les plus brefs délais et, en tout état de cause, dans un délai d'un mois à compter de la réception de votre demande. Si nécessaire, ce délai peut être prolongé de deux mois supplémentaires, en fonction de la complexité de la demande, et nous vous en informerons.</Text>
            <Text style={styles.paragraph}>Si vous estimez que nous avons violé vos droits en matière de protection des données, vous avez le droit de déposer une plainte auprès de l'autorité de protection des données compétente dans votre pays, comme la CNIL en France.</Text>

            <Text style={styles.section}>7. Cookies et technologies similaires</Text>
            <Text style={styles.paragraph}>Pour améliorer votre expérience sur Supchat et analyser l'utilisation de notre application, nous utilisons des cookies et d'autres technologies similaires. Ces technologies nous aident à personnaliser votre expérience, à vous offrir des fonctionnalités spécifiques et à améliorer la performance de l'application. Elles nous permettent également de mieux comprendre la façon dont vous utilisez notre service, afin d'en améliorer la qualité.</Text>
            <Text style={styles.paragraph}>Un cookie est un petit fichier texte qui est stocké sur votre appareil (ordinateur, smartphone, etc.) lorsque vous visitez notre site ou utilisez notre application. Il peut contenir des informations telles que votre identifiant utilisateur, vos préférences, ou des informations relatives à votre activité sur notre application. En plus des cookies, nous pouvons utiliser des technologies similaires telles que les balises web, les pixels invisibles et les scripts qui aident à collecter des informations sur l'interaction des utilisateurs avec nos services.</Text>
            <Text style={styles.paragraph}>Les cookies que nous utilisons peuvent être classés comme suit :</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Cookies nécessaires :</Text> Ces cookies sont essentiels au bon fonctionnement de notre application. Ils permettent de vous connecter, d'assurer la sécurité de vos sessions et d'exécuter des fonctions de base. Sans ces cookies, certains services ne peuvent pas être fournis.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Cookies de performance :</Text> Ces cookies nous permettent de collecter des informations sur la manière dont vous utilisez notre application, par exemple les pages que vous consultez et les erreurs éventuelles que vous pourriez rencontrer. Ces informations nous aident à améliorer la performance de notre service.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Cookies fonctionnels :</Text> Ces cookies nous aident à mémoriser vos préférences, telles que la langue ou la région dans laquelle vous vous trouvez, afin de personnaliser votre expérience d'utilisation. Ils permettent également de vous offrir des fonctionnalités améliorées.</Text>
            <Text style={styles.paragraph}>• <Text style={styles.bold}>Cookies de ciblage et publicitaires :</Text> Ces cookies sont utilisés pour vous proposer des publicités adaptées à vos centres d'intérêt. Ils peuvent également être utilisés pour limiter le nombre de fois où vous voyez une publicité ou pour mesurer l'efficacité de la publicité diffusée.</Text>
            <Text style={styles.paragraph}>Vous pouvez gérer ou désactiver les cookies via les paramètres de votre navigateur. La plupart des navigateurs vous permettent de bloquer ou de supprimer les cookies, ou de configurer une alerte lorsqu'un cookie est placé sur votre appareil. Si vous choisissez de désactiver certains cookies, cela pourrait affecter certaines fonctionnalités de notre application et réduire l'efficacité de votre expérience utilisateur.</Text>
            <Text style={styles.paragraph}>Nous nous engageons à respecter votre vie privée et à ne collecter des informations via des cookies que dans le respect des législations en vigueur. Si vous avez des questions ou des préoccupations concernant l'utilisation des cookies, n'hésitez pas à nous contacter.</Text>

            <Text style={styles.section}>8. Modifications de cette politique de confidentialité</Text>
            <Text style={styles.paragraph}>Nous nous réservons le droit de modifier cette politique de confidentialité à tout moment, afin de refléter les évolutions légales, techniques ou commerciales. Toute modification sera publiée sur cette page, et si les changements sont significatifs, nous nous engageons à vous en informer par le biais de notifications dans notre application ou par e-mail, en fonction de la nature de la modification.</Text>
            <Text style={styles.paragraph}>Nous vous encourageons à consulter régulièrement cette politique de confidentialité pour être informé de la manière dont nous protégeons vos informations. Les modifications seront appliquées à partir de la date de publication sur cette page, sauf indication contraire. Votre utilisation continue de notre application après la publication de la version mise à jour de la politique de confidentialité constitue votre acceptation des modifications apportées.</Text>
            <Text style={styles.paragraph}>Si vous avez des questions ou des préoccupations concernant les modifications apportées à cette politique, n'hésitez pas à nous contacter. Nous restons engagés à assurer la transparence et à protéger vos informations personnelles conformément à la loi.</Text>

            <Text style={styles.section}>9. Contactez-nous</Text>
            <Text style={styles.paragraph}>
              Si vous avez des questions concernant cette politique de confidentialité ou la manière dont nous traitons vos informations personnelles,
              veuillez nous contacter à l'adresse suivante :
              <Text style={styles.link} onPress={() => Linking.openURL("mailto:support@supchat.com")}> support@supchat.com</Text>.
            </Text>

            <Text style={styles.line}>───────────────────────</Text>
            <Text style={styles.footer}>© 2025 Supchat. Tous droits réservés.</Text>
          </View>
        </ScrollView>
      </View>
    </View>
  );
};

export default PrivacyPage;